export const targetAudienceList = [
  { label: "Developers" },
  { label: "Students" },
  { label: "Designers" },
  { label: "Founders" },
  { label: "Marketers" },
  { label: "Entrepreneurs" },
  { label: "Product Managers" },
  { label: "Investors" },
  { label: "Freelancers" },
  { label: "Educators" },
  { label: "Researchers" },
  { label: "Consultants" },
  { label: "HR Professionals" },
  { label: "Content Creators" },
  { label: "Small Business Owners" },
  { label: "Corporate Executives" },
  { label: "Healthcare Professionals" },
  { label: "Engineers" },
  { label: "Sales Professionals" },
  { label: "Accountants" },
  { label: "Financial Analysts" },
  { label: "Lawyers" },
  { label: "Nonprofit Leaders" },
  { label: "Public Relations Specialists" },
  { label: "Customer Support Agents" },
  { label: "IT Administrators" },
  { label: "Data Scientists" },
  { label: "UX/UI Designers" },
  { label: "Digital Nomads" },
  { label: "Parents" },
  { label: "Young Professionals" },
  { label: "Environmental Advocates" },
  { label: "Public Policy Makers" },
  { label: "Supply Chain Managers" },
  { label: "Real Estate Agents" },
  { label: "Operations Managers" },
  { label: "Government Officials" },
  { label: "Journalists" },
  { label: "Venture Capitalists" },
  { label: "Artists" },
  { label: "Musicians" },
  { label: "Chefs" },
  { label: "Athletes" },
  { label: "Fitness Coaches" },
  { label: "Gamers" },
  { label: "Photographers" },
  { label: "Videographers" },
  { label: "Writers" },
  { label: "Podcasters" },
  { label: "Influencers" },
  { label: "Travelers" },
  { label: "Indie Hackers & Makers" },
  { label: "Interns" },
  { label: "Mental Health Professionals" },
  { label: "Software Architects" },
  { label: "Compliance Officers" },
  { label: "Logistics Managers" },
  { label: "Social Workers" },
];

export const contentTypesList = [
  { label: "Blog Post" },
  { label: "Social Media Post" },
  { label: "Email Newsletter" },
  { label: "Product Description" },
  { label: "Sales Page" },
  { label: "Website Copy" },
  { label: "Video Script" },
  { label: "Ad Copy" },
  { label: "Email Sequence" },
  { label: "Lead Magnet" },
  { label: "Sales Letter" },
  { label: "Press Release" },
  { label: "Whitepaper" },
  { label: "Case Study" },
];

export const industryList = [
  { label: "Technology" },
  { label: "Finance" },
  { label: "Healthcare" },
  { label: "Retail" },
  { label: "Manufacturing" },
  { label: "Construction" },
  { label: "Marketing" },
  { label: "Sales" },
  { label: "Legal" },
  { label: "Education" },
  { label: "Hospitality" },
  { label: "Real Estate" },
  { label: "Transportation & Logistics" },
  { label: "Energy & Utilities" },
  { label: "Telecommunications" },
  { label: "Media & Entertainment" },
  { label: "Food & Beverage" },
  { label: "Nonprofit & Charity" },
  { label: "Government & Public Sector" },
  { label: "Aerospace & Defense" },
  { label: "Agriculture" },
  { label: "Pharmaceuticals" },
  { label: "Automotive" },
  { label: "Fashion & Apparel" },
  { label: "Sports & Recreation" },
  { label: "Travel & Tourism" },
  { label: "E-commerce" },
  { label: "Beauty & Personal Care" },
  { label: "Human Resources" },
];
