import { Excalidraw } from "@excalidraw/excalidraw";

export default function ExcalidrawScreen() {
  return (
    <div>
      <div
        style={{
          height: "100vh",
        }}
        className="w-screen bg-red-50"
      >
        <Excalidraw
        
          initialData={{
            elements: [
              {
                type: "text",
                version: 1,
                versionNonce: 1234567890,
                isDeleted: false,
                id: "user_1",
                fillStyle: "hachure",
                strokeWidth: 1,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 50,
                y: 50,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 180,
                height: 24,
                seed: 111111111,
                groupIds: [],
                fontSize: 20,
                fontFamily: 1,
                text: "1. User opens Figma Plugin",
                baseline: 17,
                textAlign: "left",
                verticalAlign: "top",
                containerId: null,
                originalText: "1. User opens Figma Plugin",
              },
              {
                type: "rectangle",
                version: 1,
                versionNonce: 1234567891,
                isDeleted: false,
                id: "step_1_rect",
                fillStyle: "hachure",
                strokeWidth: 1,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 40,
                y: 40,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 200,
                height: 50,
                seed: 111111112,
                groupIds: [],
              },
              {
                type: "arrow",
                version: 1,
                versionNonce: 1234567892,
                isDeleted: false,
                id: "arrow_1",
                fillStyle: "hachure",
                strokeWidth: 2,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 160,
                y: 90,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 120,
                height: 0,
                seed: 111111113,
                groupIds: [],
                startBinding: null,
                endBinding: null,
                points: [
                  [0, 0],
                  [100, 0],
                ],
              },
              {
                type: "text",
                version: 1,
                versionNonce: 1234567893,
                isDeleted: false,
                id: "user_2",
                fillStyle: "hachure",
                strokeWidth: 1,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 280,
                y: 50,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 220,
                height: 24,
                seed: 111111114,
                groupIds: [],
                fontSize: 20,
                fontFamily: 1,
                text: "2. User uploads Figma design",
                baseline: 17,
                textAlign: "left",
                verticalAlign: "top",
                containerId: null,
                originalText: "2. User uploads Figma design",
              },
              {
                type: "rectangle",
                version: 1,
                versionNonce: 1234567894,
                isDeleted: false,
                id: "step_2_rect",
                fillStyle: "hachure",
                strokeWidth: 1,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 270,
                y: 40,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 240,
                height: 50,
                seed: 111111115,
                groupIds: [],
              },
              {
                type: "arrow",
                version: 1,
                versionNonce: 1234567895,
                isDeleted: false,
                id: "arrow_2",
                fillStyle: "hachure",
                strokeWidth: 2,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 510,
                y: 90,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 100,
                height: 0,
                seed: 111111116,
                groupIds: [],
                startBinding: null,
                endBinding: null,
                points: [
                  [0, 0],
                  [100, 0],
                ],
              },
              {
                type: "text",
                version: 1,
                versionNonce: 1234567896,
                isDeleted: false,
                id: "user_3",
                fillStyle: "hachure",
                strokeWidth: 1,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 620,
                y: 50,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 240,
                height: 24,
                seed: 111111117,
                groupIds: [],
                fontSize: 20,
                fontFamily: 1,
                text: "3. Plugin generates code",
                baseline: 17,
                textAlign: "left",
                verticalAlign: "top",
                containerId: null,
                originalText: "3. Plugin generates code",
              },
              {
                type: "rectangle",
                version: 1,
                versionNonce: 1234567897,
                isDeleted: false,
                id: "step_3_rect",
                fillStyle: "hachure",
                strokeWidth: 1,
                strokeStyle: "solid",
                roughness: 1,
                opacity: 100,
                angle: 0,
                x: 610,
                y: 40,
                strokeColor: "#000000",
                backgroundColor: "#ffffff",
                width: 260,
                height: 50,
                seed: 111111118,
                groupIds: [],
              },
            ],
            appState: {
              viewBackgroundColor: "#ffffff",
              gridSize: null,
            },
          }}
        />
      </div>
    </div>
  );
}
